In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
y=np.array([3,4,5])

In [5]:
print(x) 
print(y)

[1 2 3]
[3 4 5]


In [6]:
np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

# concatenate list with array

In [8]:
z=[99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  4,  5, 99, 99, 99])

In [10]:
#for 2D array
x=np.full((2,3),1)
y=np.full((2,3),9)
print(x)
print()
print(y)

[[1 1 1]
 [1 1 1]]

[[9 9 9]
 [9 9 9]]


In [14]:
#concatenate along the row
row_concatenate=np.concatenate([x,y],axis=0)

In [15]:
row_concatenate

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
row_concatenate.shape

(4, 3)

In [16]:
#concatenate along the column
column_concatenate=np.concatenate([x,y],axis=1)

In [17]:
column_concatenate

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [19]:
column_concatenate.shape

(2, 6)

# EXAMPLE

In [32]:
x1=np.array([1,2,3])
grid=np.array([[9,8,7],[5,6,4]])

In [33]:
np.concatenate([x1,grid],axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [34]:
x2=x1.reshape(1,3)
x2

array([[1, 2, 3]])

In [35]:
np.concatenate([x2,grid],axis=0)

array([[1, 2, 3],
       [9, 8, 7],
       [5, 6, 4]])

In [38]:
#vstack is concatenate between any dimension 
#vertically stack the arrays
np.vstack([x1,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [5, 6, 4]])

In [39]:
grid

array([[9, 8, 7],
       [5, 6, 4]])

In [45]:
y=np.array([[99]
            ,[99]])

# concatenate horizantally stack the array

In [43]:
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 5,  6,  4, 99]])