In [1]:
import numpy as np 

In [2]:
x=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [3]:
x_sub=x[:2,:2]

In [4]:
x_sub

array([[12,  5],
       [ 7,  6]])

In [5]:
x_sub[0,0]=99

In [6]:
x_sub

array([[99,  5],
       [ 7,  6]])

In [7]:
x_sub2=x[:2,:2].copy()

In [9]:
x_sub2

array([[99,  5],
       [ 7,  6]])

In [10]:
x_sub2[0,0]=15

In [11]:
x_sub2

array([[15,  5],
       [ 7,  6]])

In [12]:
x

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])