In [1]:
import numpy as np

# How to create numpy arrays ?

# from python lists 

In [4]:
myarray=np.array([1,4,2,5,3])

In [5]:
myarray

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.4,5,6,7,8]) #all elements are considered of the same type

array([3.4, 5. , 6. , 7. , 8. ])

In [14]:
np.array([1,2,3,4], dtype='float32') #to explicity set the data type

array([1., 2., 3., 4.], dtype=float32)

# How to create array from scratch?

In [16]:
#Create a length-10 integer array filled with zeros
# size of array=10
#type of array =int
np.zeros(10 ,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros((10,3) ,dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
# create a3x5 floating-point array filled with 1s
#number of rows=3
#number of columns=5
np.ones((3,5) ,dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((3,2,5) ,dtype=float)
#number of rows =2
#number of column=5
#number of matrics=3

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## Data Types

# i will search on the internet about datatypes

# to get documentation for any thing shift+tab

# in the document i found [ ] and this meaning it is optional with out practice meaning Mandatory

In [23]:
#now i will create array all elements the same number
np.full((2,3),2.75)

array([[2.75, 2.75, 2.75],
       [2.75, 2.75, 2.75]])

In [24]:
# now will create array filled with linear squence (with specific range)
#starting at 0,ending at 20 ,stepping by 2

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
#end -1
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#create a 3x3 array of uniformly distributed 
#random values between 0,1

np.random.random((3,3))

array([[0.84190032, 0.41918816, 0.40681253],
       [0.78860612, 0.54881363, 0.57609776],
       [0.12293931, 0.53000372, 0.39648867]])

In [28]:
#create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[3, 7, 4],
       [5, 5, 1],
       [3, 0, 9]])

In [30]:
#create a 3x3 identity matrix
#diagonal =1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
#create an uninitialized array of three integres
#the value will be what ever happen to already exist at that memory location

np.empty((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])