In [1]:
import numpy as np

In [12]:
x=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])

In [14]:
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [16]:
x[0:2,2]

array([2, 8])

In [17]:
x[0:2,0:3] #Two rows,three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [18]:
x[1,1:3]

array([6, 8])

In [22]:
x[:3,::2] # all rows and first column and leave one 

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [23]:
x[1:,3:]

array([[8],
       [7]])

In [26]:
x[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [30]:
x[:2,::-1]

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7]])

In [31]:
x[::-1,:]

array([[ 1,  6,  7,  7],
       [ 7,  6,  8,  8],
       [12,  5,  2,  4]])

# Accessing Arrays Rows And Columns

In [34]:
#first column of array x 
x[:,:1]

array([[12],
       [ 7],
       [ 1]])

In [35]:
#first row of array x
x[0:1,:]

array([[12,  5,  2,  4]])

In [36]:
x[0]

array([12,  5,  2,  4])