In [1]:
import numpy as np

In [29]:
x=np.zeros((3,4,5),dtype='int64')

In [30]:
x

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

# these attributes to get relevant information about matrix

In [4]:
print("x ndim",x.ndim)
print("x shape:",x.shape)
print("x size",x.size) # size meaning Number of elements in array

x ndim 3
x shape: (3, 4, 5)
x size 60


# to know type of array

In [5]:
print("dtype:",x.dtype)

dtype: int64


# Array indexing

In [6]:
x1=np.array([5,0,3,3,7,9])
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
x1[3]

3

In [9]:
x1[-1]

9

In [10]:
x1[-2]

7

In [11]:
x2=np.array([[3,5,2,4],[7,6,8,8],[1,6,7,7]])

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
print(x2.shape)

(3, 4)


In [14]:
x2[0,1]

5

In [15]:
x2[0,0]

3

In [16]:
x2[-1,-1]

7

In [17]:
x2[-2,-1]

8

In [18]:
x2[-1,-3]

6

In [19]:
x2[-2,-3]

6

# if i want to chang element in this array 

In [20]:
x2[-1,-3]=2

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 2, 7, 7]])

In [33]:
x3=np.zeros((3,2,1),dtype=int)

In [34]:
x3

array([[[0],
        [0]],

       [[0],
        [0]],

       [[0],
        [0]]])

In [40]:
x3=np.array([[[1,2],[3,4]],
         [[5,6],[6,7]],
         [[8,8],[9,2]]])
x3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]],

       [[8, 8],
        [9, 2]]])

In [41]:
x4=np.array([[[1,2],[3,4]],
             [[6,7],[8,9]],
             [[10,8],[5,8]],
             [[9,10],[2,1]]])
x4.shape

(4, 2, 2)