In [1]:
import numpy as np

In [2]:
grid=np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
grid=np.arange(0,12).reshape((6,2))

In [6]:
grid

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
x=np.array([1,2,3])
#to make it two dimensional to be vector
x.reshape(1,3) 
#one row and 3 column


array([[1, 2, 3]])

In [8]:
#cloumn vector
x.reshape(3,1)

array([[1],
       [2],
       [3]])

# anthor method

In [9]:
x2=np.array([1,2,3])
x2.ndim

1

In [10]:
#rowvector
x2=x2[np.newaxis, :]

In [11]:
x2

array([[1, 2, 3]])

In [12]:
x2.shape

(1, 3)

In [13]:
x3=np.array([4,5,6])

In [14]:
x3=x3[:,np.newaxis]

In [15]:
x3

array([[4],
       [5],
       [6]])

In [16]:
x3.shape

(3, 1)

In [17]:
grid

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
grid.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# (-1) check the number we put 

In [21]:
grid.reshape(2,3,-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [22]:
grid.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [23]:
grid.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
grid.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])