# Array slicing:Accessing Subarrays
# one -dimensional subarrays

In [1]:
import numpy as np

In [2]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[1:5]

array([1, 2, 3, 4])

In [4]:
x[:3]#first three elements

array([0, 1, 2])

In [5]:
x[5:]#elements after 5 

array([5, 6, 7, 8, 9])

In [6]:
x[4:7]

array([4, 5, 6])

In [13]:
x2=np.random.randint(2,20,10)
x2

array([ 6, 14, 13, 17, 19,  8, 18, 18, 13, 18])

In [9]:
x2[4:6]

array([ 5, 12])

# if i want to take number and leave the next number 

In [11]:
x2[::2] 

array([8, 9, 5, 3, 8])

In [12]:
# if i want to take the first number and leave 3 number 
x2[::3]

array([ 8, 12,  3, 18])

In [14]:
#if i want start from specific index
x2[1::2]

array([14, 17,  8, 18, 18])

In [15]:
# all element reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
# all element reversed
x2[::-1]

array([18, 13, 18, 18,  8, 19, 17, 13, 14,  6])

In [17]:
x2[2::-1]

array([13, 14,  6])

In [18]:
x2[10::-1]

array([18, 13, 18, 18,  8, 19, 17, 13, 14,  6])

In [20]:
x2[5::-2]

array([ 8, 17, 14])