In [1]:
import numpy as np

In [4]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3,x4=np.split(x,[2,4,6])
print(x1,x2,x3,x4)

[1 2] [ 3 99] [99  3] [2 1]


In [5]:
print(x1)
print(x2)
print(x3)
print(x4)

[1 2]
[ 3 99]
[99  3]
[2 1]


In [10]:
Grid=np.arange(16).reshape((4,4))

In [11]:
Grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
lower,upper=np.vsplit(Grid,[2])
print(lower)
print()
print(upper)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [14]:
lower,upper,last=np.vsplit(Grid,[2,3])
print(lower)
print()
print(upper)
print()
print(last)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]]

[[12 13 14 15]]


In [17]:
left,middle,right=np.hsplit(Grid,[2,3])
print(left)
print()
print(middle)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2]
 [ 6]
 [10]
 [14]]

[[ 3]
 [ 7]
 [11]
 [15]]
